service: management-suite

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getUser:
    handler: ./dist\handlers/http/users/user/get.handler
    events:
      - http:
          path: /users/{userId}
          method: get
  deleteUser:
    handler: ./dist\handlers/http/users/user/delete.handler
    events:
      - http:
          path: /users/{userId}
          method: delete
  postUser:
    handler: ./dist\handlers/http/users/user/post.handler
    events:
      - http:
          path: /users
          method: post
  getUsers:
    handler: ./dist\handlers\http\users\get.handler  
    events:
      - http:
          path: /users
          method: get
plugins:
  - serverless-offline



