openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /dev/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        address:
                          type: string
                        phone:
                          type: string
                        email:
                          type: string

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string
                    example: SERVER_ERROR
